version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "dauly"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/help/" # Location of package manifests
    schedule:
      interval: "daily"
